public enum Estados {
    INICIO, FIM, MENOR, MAIOR, IDENTIFICADOR, INICIO_COMENTARIO, FIM_COMENTARIO, COMENTARIO,
    PRIMEIRO_DECIMAL, DECIMAL, DIGITO, HEXADECIMAL1, DIVISAO,
    HEXADECIMAL2, CARACTER1, CARACTER2, CARACTER3, STRING, IGUAL, EXCLAMACAO, HEXA_ID;
}